#!/bin/bash
# $1 = the name of the script
# $2 = pattern for functions (optional)
list_functions(){
	if [ "$2" == "" ]; then
		find ./ -name $1 -exec cat {} \; |  grep -n 'func '
	else
		find ./ -name $1 -exec cat {} \; |  grep -n 'func ' | grep $2
	fi
}


godot_accessor(){
	name=${1#"_"}
	tab=$'\t'

	read -r -d '' OUTPUT  <<EOM
func get_$name():
${tab}return $1

func set_$name($name):
${tab}$1 = $name
EOM
  echo "$OUTPUT"
	echo "$OUTPUT" | pbcopy
}

alias godot_loc="find . -name '*.gd' | xargs wc -l"
