#!/bin/bash

#these are profile files to include
dotit() {
  if [ -f "$BASHFILES/$1" ] ; then
    eval ". $BASHFILES/$1"
  fi
}

#old "local" file is now pre_local
#local should be removed and replaced
#with pre_local

dotit pre_local
dotit main
#dotit text_format
dotit post_local
