#!/bin/bash

proxify ()
{
    export HTTP_PROXY=http://http-proxy.ae.ge.com:80;
    export HTTPS_PROXY=http://http-proxy.ae.ge.com:80;
    export NO_PROXY=localhost,127.0.1.1
}

unproxify ()
{
    unset HTTP_PROXY;
    unset HTTPS_PROXY
}

prox ()
{
    DEFAULT_GATEWAY=$(route PRINT | grep ' 0\.0\.0\.0' | head -n 1 | awk '{print $4}');
    ps -aWl | grep stunnel >/dev/null;
    stunnelresult=$?;
    if [[ $DEFAULT_GATEWAY == 3.* ]]; then
        PROXY="http-proxy.ae.ge.com:80";
        echo "On GE Network setting proxy to $PROXY and unsetting git proxy settings";
        git config --global --unset http.proxy;
        git config --global --unset https.proxy;
        export HTTP_PROXY=http://$PROXY;
        export HTTPS_PROXY=http://$PROXY;
        export NO_PROXY=localhost,127.0.1.1,.rubygems.org,supermarket.chef.io,s3.amazonaws.com;
    elif [ "${stunnelresult}" -eq "0" ]; then
        PROXY="127.0.0.1:31114";
        echo "On GE MyApps setting proxy to $PROXY and setting git proxy settings";
        git config --global https.proxy $PROXY;
        git config --global http.proxy $PROXY;
        export HTTP_PROXY=http://$PROXY;
        export HTTPS_PROXY=http://$PROXY;
        export NO_PROXY=localhost,127.0.1.1,sts.amazonaws.com,ec2.us-east-1.amazonaws.com,.amazonaws.com,.rubygems.org,supermarket.chef.io,s3.amazonaws.com;
    else
        echo "Not on any GE network, unsetting everything";
        git config --global --unset https.proxy;
        git config --global --unset http.proxy;
        unset HTTP_PROXY;
        unset HTTPS_PROXY;
        unset NO_PROXY;
    fi
}